MvcWebUI/Controllers/SepetController.cs
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace MvcWebUI.Controllers
{
    [Authorize]
    public class SepetController : Controller
    {
        private readonly IUrunService _urunService;

        public SepetController(IUrunService urunService)
        {
            _urunService = urunService;
        }

        public IActionResult Ekle(int? urunId)
        {
            if (urunId == null)
                return View("Hata", "Ürün Id gereklidir!");
            UrunModel urun = _urunService.Query().SingleOrDefault(u => u.Id == urunId);
            if (urun == null)
                return View("Hata", "Ürün bulunamadı!");

            // eğer stokta ürün varsa sepete eklenebilsin
            if (urun.StokMiktari == 0)
            {
                TempData["Sonuc"] = "Sepete eklenmek istenen ürün stokta bulunmamaktadır!";
                return RedirectToAction("Index", "Urunler", new { sepetUrunId = urun.Id });
            }

            SepetElemanModel eleman;
            List<SepetElemanModel> sepet;
            string sepetJson;
            sepet = SessiondanSepetiGetir();
            eleman = new SepetElemanModel()
            {
                UrunId = urunId.Value,
                KullaniciId = Convert.ToInt32(User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value),
                UrunAdi = urun.Adi,
                UrunBirimFiyati = urun.BirimFiyati ?? 0
            };
            sepet.Add(eleman);
            int urunAdedi = sepet.Count(s => s.UrunId == urunId);

            // eklenen ürünün adedi ürün stok miktarini aşmamalı
            if (urunAdedi > urun.StokMiktari)
            {
                TempData["Sonuc"] = "Sepete eklenen ürün adedi ürün stok miktarından fazladır!";
            }
            else
            {
                sepetJson = JsonConvert.SerializeObject(sepet);
                // Session'da asla kullanıcı bilgileri gibi kritik veriler tutulmamalıdır!
                HttpContext.Session.SetString("sepet", sepetJson);
                TempData["Sonuc"] = urunAdedi + " adet " + eleman.UrunAdi + " sepete eklendi.";
            }
            
            return RedirectToAction("Index", "Urunler", new { sepetUrunId = eleman.UrunId });
        }

        private List<SepetElemanModel> SessiondanSepetiGetir()
        {
            List<SepetElemanModel> sepet = new List<SepetElemanModel>();
            string sepetJson = HttpContext.Session.GetString("sepet");
            if (!string.IsNullOrWhiteSpace(sepetJson)) // byte[], int veya string olarak session'da veri kullanılabilir
            {
                sepet = JsonConvert.DeserializeObject<List<SepetElemanModel>>(sepetJson);
            }
            return sepet;
        }

        public IActionResult Getir()
        {
            List<SepetElemanModel> sepet = SessiondanSepetiGetir();

            // session'dan alınan sepetin sisteme giriş yapan kullanıcı Id'sine göre filtrelenmesi:
            sepet = sepet.Where(s => s.KullaniciId == Convert.ToInt32(User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value)).ToList();

            List<SepetElemanGroupByModel> sepetGroupBy = (from s in sepet
                                                              //group s by s.UrunAdi // tek bir özellik gruplanıyorsa kullanılır
                                                          group s by new { s.UrunId, s.KullaniciId, s.UrunAdi } // birden çok özellik gruplanıyorsa kullanılır
                                                         into sGroupBy
                                                          select new SepetElemanGroupByModel()
                                                          {
                                                              UrunId = sGroupBy.Key.UrunId,
                                                              KullaniciId = sGroupBy.Key.KullaniciId,
                                                              UrunAdi = sGroupBy.Key.UrunAdi,
                                                              ToplamUrunBirimFiyati = sGroupBy.Sum(sgb => sgb.UrunBirimFiyati),
                                                              ToplamUrunBirimFiyatiDisplay = sGroupBy.Sum(sgb => sgb.UrunBirimFiyati).ToString("C2"),
                                                              ToplamUrunAdedi = sGroupBy.Count()
                                                          }).ToList();

            sepetGroupBy = sepetGroupBy.OrderBy(s => s.UrunAdi).ToList();

            //return View(sepet);
            return View("GetirGroupBy", sepetGroupBy);
        }

        public IActionResult Temizle()
        {
            // kullanıcıdan bağımsız session'daki sepet anahtarına sahip tüm verilerin silinmesi:
            //HttpContext.Session.Remove("sepet");

            // kullanıcıya ait session'daki sepet anahtarına sahip verilerin silinmesi:
            List<SepetElemanModel> sepet = new List<SepetElemanModel>();
            string sepetJson = HttpContext.Session.GetString("sepet");
            if (!string.IsNullOrWhiteSpace(sepetJson))
            {
                sepet = JsonConvert.DeserializeObject<List<SepetElemanModel>>(sepetJson);
            }
            // session'dan alınan sepetin sisteme giriş yapan kullanıcı Id'sine göre filtrelenmesi:
            List<SepetElemanModel> kullaniciSepeti = sepet.Where(s => s.KullaniciId == Convert.ToInt32(User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value)).ToList();
            foreach (SepetElemanModel eleman in kullaniciSepeti)
            {
                sepet.Remove(eleman);
            }
            sepetJson = JsonConvert.SerializeObject(sepet);
            HttpContext.Session.SetString("sepet", sepetJson);

            TempData["Sonuc"] = "Sepet temizlendi.";
            return RedirectToAction(nameof(Getir));
        }

        public IActionResult Sil(int? urunId, int? kullaniciId)
        {
            if (!urunId.HasValue || !kullaniciId.HasValue)
                return View("Hata", "Ürün Id ve Kullanıcı Id gereklidir!");
            List<SepetElemanModel> sepet = SessiondanSepetiGetir();
            SepetElemanModel eleman = sepet.FirstOrDefault(s => s.UrunId == urunId.Value && s.KullaniciId == kullaniciId.Value);
            if (eleman != null)
            {
                sepet.Remove(eleman);
                HttpContext.Session.SetString("sepet", JsonConvert.SerializeObject(sepet));
                TempData["Sonuc"] = "Ürün sepetten silindi.";
            }
            return RedirectToAction(nameof(Getir));
        }
    }
}

MvcWebUI/Controllers/UrunlerController.cs
using AppCore.Business.Models.Results;
using Business.Models;
using Business.Services;
using Business.Services.Bases;
using DataAccess.Contexts;
using DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcWebUI.Settings;

namespace MvcWebUI.Controllers
{
    [Authorize]
    public class UrunlerController : Controller
    {
        //private readonly ETicaretContext _context;

        //public UrunlerController(ETicaretContext context)
        //{
        //    _context = context;
        //}

        private readonly IUrunService _urunService;
        private readonly IKategoriService _kategoriService;

        private readonly IMagazaService _magazaService;

        public UrunlerController(IUrunService urunService, IKategoriService kategoriService, IMagazaService magazaService)
        {
            _urunService = urunService;
            _kategoriService = kategoriService;

            _magazaService = magazaService;
        }

        // GET: Urunler
        //public IActionResult Index()
        //{
        //    var eTicaretContext = _context.Urunler.Include(u => u.Kategori);
        //    return View(eTicaretContext.ToList());
        //}
        [AllowAnonymous] // controller üzerindeki Authorize attribute'unu devre dışı bırakarak herkesin aksiyona ulşamasını sağlar.
        // Sepete ekleme işlemi sonucunda eklenen ürün ID'si üzerinden mesaj gösterilmesi için değiştirildi
        //public IActionResult Index()
        //{
        //    List<UrunModel> model = _urunService.Query().ToList();
        //    return View(model);
        //}
        public IActionResult Index(int? sepetUrunId)
        {
            List<UrunModel> urunler = _urunService.Query().ToList();
            if (sepetUrunId.HasValue)
            {
                UrunModel urun = urunler.SingleOrDefault(u => u.Id == sepetUrunId.Value);
                urun.SepeteEklendiMi = true;
            }
            return View(urunler);
        }

        // GET: Urunler/Details/5
        //public IActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var urun = _context.Urunler
        //        .Include(u => u.Kategori)
        //        .SingleOrDefault(m => m.Id == id);
        //    if (urun == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(urun);
        //}
        //[Authorize(Roles = "Admin,Kullanıcı")]
        public IActionResult Details(int? id)
        {
            if (id == null)
                return View("Hata", "Id gereklidir!");
            UrunModel model = _urunService.Query().SingleOrDefault(u => u.Id == id.Value);
            if (model == null)
                return View("Hata", "Kayıt bulunamadı!");
            return View(model);
        }

        // GET: Urunler/Create
        //public IActionResult Create()
        //{
        //    ViewData["KategoriId"] = new SelectList(_context.Kategoriler, "Id", "Adi");
        //    return View();
        //}
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            List<KategoriModel> kategoriler = _kategoriService.Query().ToList();
            ViewBag.KategoriId = new SelectList(kategoriler, "Id", "Adi");

            ViewBag.Magazalar = new MultiSelectList(_magazaService.Query().ToList(), "Id", "Adi");

            // model üzerinden bazı ilk verilerin atanması
            //return View();
            UrunModel model = new UrunModel()
            {
                BirimFiyati = 0,
                StokMiktari = 0
            };
            return View(model);
        }

        // POST: Urunler/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public IActionResult Create(Urun urun)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(urun);
        //        _context.SaveChanges();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["KategoriId"] = new SelectList(_context.Kategoriler, "Id", "Adi", urun.KategoriId);
        //    return View(urun);
        //}
        [Authorize(Roles = "Admin")]
        //public IActionResult Create(UrunModel urun) // form üzerinden gönderilen imaj dosyasını kullanabilmek için değiştirildi (form'daki input type file HTML elemanının name attribute'una dikkat!)
        public IActionResult Create(UrunModel urun, IFormFile imaj)
        {
            if (ModelState.IsValid)
            {
                // İmaj dosya adları olarak ürünün Id'si ile yüklenen imajın dosya uzantısını kullanacağımızdan Id veritabanında ekleme işlemi sonucunda otomatik oluşacaktır, ancak dosya uzantısını servise göndermek ve dolayısıyla da tabloya kaydetmek zorundayız.
                ImajDosyaUzantisiniGuncelle(urun, imaj); // urun parametresi referans tip olduğu için method içinde güncellenecek ve sonucu urun üzerinden dışarıya yansıyacaktır

                var result = _urunService.Add(urun);
                if (result.IsSuccessful)
                {
                    bool? imajKaydetSonuc = ImajKaydet(urun, imaj);
                    if (imajKaydetSonuc == false) // imaj uzantı ve boyut validasyonlarını geçememiş demektir
                    {
                        result.Message += $" İmaj yüklenemedi! Yüklenen imaj uzantıları {AppSettings.ImajDosyaUzantilari} uzantılarından biri ve boyutu maksimum {AppSettings.ImajMaksimumDosyaBoyutu} mega byte olmalıdır!";
                    }
                    TempData["Success"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            ViewBag.KategoriId = new SelectList(_kategoriService.Query().ToList(), "Id", "Adi", urun.KategoriId);

            ViewBag.Magazalar = new MultiSelectList(_magazaService.Query().ToList(), "Id", "Adi", urun.MagazaIdleri);

            return View(urun);
        }

        private bool? ImajKaydet(UrunModel model, IFormFile yuklenenImaj, bool uzerineYazilsinMi = false)
        {
            #region Dosya validasyonu
            bool? sonuc = null; // flag, sonuc'un null dönmesi demek kullanıcının dosya seçip yüklememesi demek
            string yuklenenDosyaAdi = null, yuklenenDosyaUzantisi = null;
            if (yuklenenImaj != null && yuklenenImaj.Length > 0) // yüklenen imaj verisi varsa
            {
                sonuc = false; // validasyonu geçemedi ilk değer ataması
                yuklenenDosyaAdi = yuklenenImaj.FileName; // asusrog.jpg
                yuklenenDosyaUzantisi = Path.GetExtension(yuklenenDosyaAdi); // .jpg
                string[] imajDosyaUzantilari = AppSettings.ImajDosyaUzantilari.Split(',');
                foreach (string imajDosyaUzantisi in imajDosyaUzantilari)
                {
                    if (yuklenenDosyaUzantisi.ToLower() == imajDosyaUzantisi.ToLower().Trim())
                    {
                        sonuc = true; // imaj uzantısı validasyonunu geçti
                        break;
                    }
                }
                if (sonuc == true) // eğer imaj uzantısı validasyonunu geçtiyse imaj boyutunu valide edelim
                {
                    // 1 byte = 8 bits
                    // 1 kilobyte = 1024 bytes
                    // 1 megabyte = 1024 kilobytes = 1024 * 1024 bytes = 1.048.576 bytes
                    double imajDosyaBoyutu = AppSettings.ImajMaksimumDosyaBoyutu * Math.Pow(1024, 2); // bytes
                    if (yuklenenImaj.Length > imajDosyaBoyutu)
                        sonuc = false; // imaj boyutu validasyonunu geçemedi
                }
            }
            #endregion

            #region Dosyanın kaydedilmesi
            if (sonuc == true)
            {
                // Sanal dosya yolu (virtual path): ~/wwwroot/dosyalar/urunler/asusrog.jpg
                yuklenenDosyaAdi = model.Id + yuklenenDosyaUzantisi; // 1.jpg
                string dosyaYolu = Path.Combine("wwwroot", "dosyalar", "urunler", yuklenenDosyaAdi);
                // Fiziksel dosya yolu (absolute path): C:\çağıl\ETicaretCoreBilgeAdam\MvcWebUI\wwwroot\dosyalar\urunler\asusrog.jpg

                using (FileStream fileStream = new FileStream(dosyaYolu, uzerineYazilsinMi ? FileMode.Create : FileMode.CreateNew)) // CreateNew: eğer aynı isimde dosya varsa hata verir, Create ise üzerine yazar
                {
                    yuklenenImaj.CopyTo(fileStream);
                }
            }
            #endregion

            #region Eğer varsa aynı ad ve farklı uzantıya sahip dosyanın silinmesi
            if (sonuc == true)
            {
                ImajSil(model, yuklenenDosyaUzantisi);
            }
            #endregion
            return sonuc;
        }

        private void ImajSil(UrunModel model, string yuklenenDosyaUzantisi = null) // eğer güncelleme işlemi ise yüklenen dosya uzantısı dolu geleceğinden dosya uzantısı değiştiyse eski dosya uzantısına sahip dosya silinir, eğer silme işlemi ise yüklenen dosya uzantısı null olacağından direkt mevcut dosya uzantısına sahip dosya silinir
        {
            string eskiImajDosyaUzantisi = string.IsNullOrWhiteSpace(model.ImajDosyaYoluDisplay) ? null : Path.GetExtension(model.ImajDosyaYoluDisplay); // view'da gizli olarak tuttuğumuz (ImajDosyaYoluDisplay) üzerinden kullanıcının daha önce yüklemiş olduğu dosyanın uzantısı

MvcWebUI/Views/Urunler/Delete.cshtml
@*@model DataAccess.Entities.Urun*@
@model UrunModel

@{
    ViewData["Title"] = "Ürün Sil";
}

<h1>@ViewData["Title"]</h1>

<h3>Bu ürünü silmek istediğinize emin misiniz?</h3>
<div>

    @*<h4>Urun</h4>
    <hr />
    <dl class="row">
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Adi)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Adi)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Aciklamasi)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Aciklamasi)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.BirimFiyati)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.BirimFiyati)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.StokMiktari)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.StokMiktari)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.SonKullanmaTarihi)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.SonKullanmaTarihi)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Kategori)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Kategori.Adi)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Guid)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Guid)
        </dd>
    </dl>*@
    <partial name="_Details" model="Model" />
    
    <form asp-action="Delete">
	@Html.AntiForgeryToken()
        <input type="hidden" asp-for="Id" />

        <input type="hidden" asp-for="ImajDosyaYoluDisplay" />

        <input type="submit" value="Evet" class="btn btn-danger" />&nbsp;&nbsp;
        <a asp-action="Index" class="btn btn-success">Hayır</a>
    </form>
</div>

MvcWebUI/Views/Urunler/Details.cshtml
@*@model DataAccess.Entities.Urun*@
@model UrunModel

@{
    ViewData["Title"] = "Ürün Detayı";
}

<h1>@ViewData["Title"]</h1>

@*@await Html.PartialAsync("_Details", Model)*@
<partial name="_Details" model="Model" />

<div>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model?.Id">Düzenle</a>@:&nbsp;|&nbsp;
    }
    <a asp-action="Index">Ürün Listesi</a>
</div>

MvcWebUI/Views/Urunler/Index.cshtml
@*@model IEnumerable<DataAccess.Entities.Urun>*@
@*@model List<UrunModel>*@ @* Eğer Model List tipinde tanımlanırsa aşağıda DisplayNameFor methodları kullanılamaz *@
@model IEnumerable<UrunModel>

@{
    ViewData["Title"] = "Ürün Listesi";
}

<h1>@ViewData["Title"]</h1>

@*<p>
    <a asp-action="Create">Yeni Ürün</a>
</p>*@
<p>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a asp-action="Create"><i class="fas fa-plus"></i> Yeni Ürün</a>
    }
</p>

@if (TempData["Success"] != null)
{
    <p class="text-success">@TempData["Success"]</p>
}

@*<table class="table">*@
<table id="urunler" class="display" style="width:100%">

    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.Kategori)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.KategoriAdiDisplay)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Adi)
            </th>

            @*<th>
                @Html.DisplayNameFor(model => model.Aciklamasi)
            </th>*@

            @*<th>
                @Html.DisplayNameFor(model => model.BirimFiyati)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.BirimFiyatiDisplay)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.StokMiktari)
            </th>

            @*<th>
                @Html.DisplayNameFor(model => model.SonKullanmaTarihi)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.SonKullanmaTarihiDisplay) (yıl-ay-gün)
            </th>

            @*<th>
                @Html.DisplayNameFor(model => model.Guid)
            </th>*@

            <th></th>
        </tr>
    </thead>
    <tbody>
    @if (Model != null && Model.Count() > 0)
    {
        foreach (var item in Model)
        {
            <tr>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Kategori.Adi)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.KategoriAdiDisplay)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Adi)
                </td>

                @*<td>
                    @Html.DisplayFor(modelItem => item.Aciklamasi)
                </td>*@

                @*<td>
                    @Html.DisplayFor(modelItem => item.BirimFiyati)
                </td>*@
                @* Birim fiyatın formatlanmamış hali (kullanışsız, okunması zor). *@

                @*<td>
                    @Html.DisplayFor(modelItem => item.BirimFiyati.ToString("C2", new CultureInfo("tr-TR")))
                </td>*@
                @* 
                    View'larda minimum C# kodu yazılmalı, olabildiğince model verileri kullanılmalı.
                    Birim fiyatın formatlanması view'da değil ilgili serviste yapılmalı ve formatlanan özellik (BirimFiyatiDisplay) kullanılmalı.
                *@

                <td>
                    @Html.DisplayFor(modelItem => item.BirimFiyatiDisplay)
                </td>
                @* Birim fiyatın ihtiyacımız olan ilgili servis tarafından formatlanmış hali. *@

                <td>
                    @Html.DisplayFor(modelItem => item.StokMiktari)
                </td>

                @*<td>
                    @Html.DisplayFor(modelItem => item.SonKullanmaTarihi)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.SonKullanmaTarihiDisplay)
                </td>

                @*<td>
                    @Html.DisplayFor(modelItem => item.Guid)
                </td>*@

                <td style="text-align: right;">
                    @if (User.Identity.IsAuthenticated)
                    {

                        if (item.SepeteEklendiMi)
                        {
                            <partial name="_Sonuc"></partial>
                        }

                        if (item.StokMiktari > 0) // eğer stokta ürün varsa sepete eklenebilsin
                        {
                            <a asp-action="Ekle" asp-controller="Sepet" asp-route-urunId="@item.Id"><i class="fas fa-lg fa-cart-plus"></i> Sepete Ekle</a>
                            @:&nbsp;|&nbsp;
                        }

                        <a asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-lg fa-info-circle"></i> Detay</a>
                        @* fa-lg icon boyutunu 1.5 kez, fa-2x 2 kat, fa-3x 3 kat vb. büyütmek için kullanılır *@
                        if (User.IsInRole("Admin"))
                        {
                            @:&nbsp;
                            <text>|&nbsp;</text>
                            @* Razor escape işlemleri için ya @: ya da <text> tag'i kullanılır. *@

                            <a asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-lg fa-pen-square"></i> Düzenle</a>
                            @:&nbsp;|&nbsp;
                            <a asp-action="Delete" asp-route-id="@item.Id"><i class="fas fa-lg fa-trash"></i> Sil</a>
                        }
                    }
                </td>
            </tr>
        }
    }
    </tbody>
</table>

@*
    DataTables kütüphanesi tüm view'larda kullanılmayacağı için _Layout view'ında eklemek yerine
    sadece ürün listeleme sayfasında kullanılacağı Urunler -> Index view'ında Scripts section'ına
    css ve js kütüphaneleri ile birlikte eklenmelidir.
*@
@section Scripts
{
    @* https://datatables.net/ *@
    <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script>
        //$(document).ready(function() { // içerisindeki kodlar sayfanın yüklenmesi tamamlandıktan sonra çalışır
        $(function() {
            $('#urunler').DataTable({
                language: {
                    // Eğer kullanılan metinsel bir dosyada Türkçe karakter sorunu varsa
                    // dosya Notepad ile açılıp kodlama (encoding) UTF-8'e değiştirilerek kaydedilmelidir.
                    url: "/json/datatablesTurkish.json"
                }
            });
        });
    </script>
}

MvcWebUI/Views/Urunler/_Details.cshtml
@model UrunModel

<div>
    <h4>Ürün</h4>
    <hr />
    <dl class="row">
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Adi)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Adi)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Aciklamasi)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Aciklamasi)
        </dd>

        @*<dt class="col-2">
            @Html.DisplayNameFor(model => model.BirimFiyati)
            </dt>
            <dd class="col-10">
            @Html.DisplayFor(model => model.BirimFiyati)
            </dd>*@
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.BirimFiyatiDisplay)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.BirimFiyatiDisplay)
        </dd>

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.StokMiktari)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.StokMiktari)
        </dd>

        @*<dt class="col-2">
            @Html.DisplayNameFor(model => model.SonKullanmaTarihi)
            </dt>
            <dd class="col-10">
            @Html.DisplayFor(model => model.SonKullanmaTarihi)
            </dd>*@
        @if (!string.IsNullOrWhiteSpace(Model.SonKullanmaTarihiDisplay))
        {
            <dt class="col-2">
                @Html.DisplayNameFor(model => model.SonKullanmaTarihiDisplay) (yıl-ay-gün)
            </dt>
            <dd class="col-10">
                @Html.DisplayFor(model => model.SonKullanmaTarihiDisplay)
            </dd>
        }

        @*<dt class="col-2">
            @Html.DisplayNameFor(model => model.Kategori)
            </dt>
            <dd class="col-10">
            @Html.DisplayFor(model => model.Kategori.Adi)
            </dd>*@
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.KategoriAdiDisplay)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.KategoriAdiDisplay)
        </dd>

        @*<dt class="col-2">
            @Html.DisplayNameFor(model => model.Guid)
            </dt>
            <dd class="col-10">
            @Html.DisplayFor(model => model.Guid)
            </dd>*@

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.ImajDosyaYoluDisplay)
        </dt>
        <dd class="col-10">
            @if (!string.IsNullOrWhiteSpace(Model.ImajDosyaYoluDisplay))
            {
                <div style="width:40%;">
                    <img src="@Model.ImajDosyaYoluDisplay" class="img-fluid" />
                </div>
            }
        </dd>

        @* Ürün mağazaları: *@
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.MagazalarDisplay)
        </dt>
        <dd class="col-10">
            <ol style="padding: 0;">
                @foreach (string magaza in Model.MagazalarDisplay)
                {
                    <li>@magaza</li>
                }
            </ol>
        </dd>
    </dl>
</div>