MvcWebUI/Controllers/KategorilerController.cs
using AppCore.Business.Models.Results;
using Business.Models;
using Business.Services;
using Business.Services.Bases;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MvcWebUI.Controllers
{
    public class KategorilerController : Controller
    {
        // Bu class'ın ihtiyacı olan objeleri class içinde new'lemek yerine dependency injection
        // (constructor injection) yapılmalı.
        //private readonly IKategoriService _kategoriService = new KategoriService();

        private readonly IKategoriService _kategoriService;

        public KategorilerController(IKategoriService kategoriService)
        {
            _kategoriService = kategoriService;
        }

        //[Authorize(Roles = "Admin,Kullanıcı")]
        [Authorize] // sisteme giriş yapmış (authentication cookie'si) olan kullanıcılar bu aksiyonu çalıştırabilir
        public IActionResult Index() // ~/Kategoriler/Index
        {
            List<KategoriModel> kategoriler = _kategoriService.Query().ToList();
            // ToList(), SingleOrDefault(), FirstOrDefault(), vb. methodlar Query ile
            // oluşturulan sorguyu veritabanında çalıştırır ve sonucunu bir objeye atar.

            if (kategoriler == null || kategoriler.Count == 0) // liste boş ise
                return View("Hata", "Kayıt bulunamadı.");

            //return View(); // Index.cshtml'i kullanır
            return View("KategoriListesi", kategoriler); // KategoriListesi.cshtml'i kullanır
        }

        // ~/Kategoriler/OlusturGetir
        [HttpGet] // Action Method Selector:
                  // Web server'da herhangi bir kaynak getirip client'e dönmek için kullanılır.
                  // eğer bir aksiyona herhangi bir Http attribute'u yazılmazsa default'u get'tir.
        [Authorize(Roles = "Admin")] // sisteme giriş yapmış (authentication cookie'si) olan ve Admin rolündeki kullanıcılar bu aksiyonu çalıştırabilir
        public IActionResult OlusturGetir() // önce kullanıcıya giriş yapabileceği form sayfası getirilir
        {
            return View("OlusturHtml");
        }

        // ~/Kategoriler/OlusturGonder
        [HttpPost] // Client'ın web server'a veri göndermesi için kullanılır.
                   // Genelde HTML form'ları üzerinden method post olarak kullanılır.
                   // Eğer post (gönderme) işlemi yapılıyorsa HttpPost mutlaka yazılmalıdır.
        [Authorize(Roles = "Admin")]
        public IActionResult OlusturGonder(string Adi, string Aciklamasi) // kullanıcının girdiği kategori verileri gönderilir ve veritabanında oluşturulur
        {
            if (string.IsNullOrWhiteSpace(Adi))
                return View("Hata", "Kategori adı zorunludur!");
            if (Adi.Length > 100)
                return View("Hata", "Kategori adı en fazla 100 karakter olmalıdır!");
            if (!string.IsNullOrWhiteSpace(Aciklamasi) && Aciklamasi.Length > 4000)
                return View("Hata", "Kategori açıklaması en fazla 4000 karakter olmalıdır!");

            KategoriModel model = new KategoriModel()
            {
                Adi = Adi,
                Aciklamasi = Aciklamasi
            };

            Result result = _kategoriService.Add(model);
            if (result.IsSuccessful)
            {

                //return RedirectToAction("Index");
                return RedirectToAction(nameof(Index));

            }
            return View("Hata", result.Message); // status code: 200 (OK)
        }

        //https://httpstatuses.com/
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id) // ~/Kategoriler/Edit/5
        {
            //if (id == null)
            if (!id.HasValue)
            {
                //return BadRequest(); // status code: 400
                //return BadRequest("Id gereklidir!");
                return View("Hata", "Id gereklidir!");
            }

            //KategoriModel model = _kategoriService.Query().SingleOrDefault(k => k.Id == id);
            KategoriModel model = _kategoriService.Query().SingleOrDefault(k => k.Id == id.Value);

            if (model == null)
            {
                //return NotFound(); // status code: 404
                //return NotFound("Kayıt bulunamadı!");
                return View("Hata", "Kayıt bulunamadı!");
            }

            //return new ViewResult();
            return View(model); // status code: 200 (OK)
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(KategoriModel model) // ~/Kategoriler/Edit
        {
            if (ModelState.IsValid) // modelde validasyon hataları yoksa
            {
                var result = _kategoriService.Update(model);
                if (result.IsSuccessful)
                {
                    // TempData: eğer yönlendirme (redirect) işlemi varsa yönlendirilen aksiyon üzerinden dönen view'a
                    // string bir index üzerinden herhangi bir obje taşımak için kullanılır.
                    TempData["Success"] = result.Message; // Kategori başarıyla güncellendi.

                    return RedirectToAction(nameof(Index));
                }

                // eğer servis başarısız sonucu döndüyse:

                // ViewData veya ViewBag: eğer view dönülüyorsa string bir index üzerinden view'a herhangi bir obje taşımak için kullanılır.
                // ViewBag (özellik) ile ViewData (index) birbirleri yerine aynı özellik ve index adları üzerinden kullanılabilir.
                //ViewData["Error"] = result.Message; // Girdiğiniz kategori adına sahip kayıt bulunmaktadır!
                ViewBag.Error = result.Message;
            }

            // eğer modelde validasyon hataları varsa
            return View(model);
        }

        //[Authorize(Roles = "Admin")] // alternatif olarak aşağıda olduğu gibi User objesi üzerinden de kimlik kontrolü yapılabilir
        public IActionResult Delete(int? id) // ~/Kategoriler/Delete/5
        {
            //if (!User.Identity.IsAuthenticated || !User.IsInRole("Admin")) // kullanici giriş yapmamış ve Admin rolünde değil, bunun yerine Authorize attribute kullanımı genelde tercih edilmeli
            if (!(User.Identity.IsAuthenticated && User.IsInRole("Admin")))
                return RedirectToAction("Giris", "Hesaplar");

            if (!id.HasValue)
                return View("Hata", "Id gereklidir!");
            var result = _kategoriService.Delete(id.Value);
            if (result.IsSuccessful)
            {
                TempData["Success"] = result.Message; // Kategori başarıyla silindi.
            }
            else
            {
                TempData["Error"] = result.Message; // Silinmek istenen kategoriye ait ürünler bulunmaktadır!
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Details(int? id) // ~/Kategoriler/Details/5
        {
            if (!id.HasValue)
                return View("Hata", "Id gereklidir!");
            KategoriModel model = _kategoriService.Query().SingleOrDefault(k => k.Id == id.Value);
            if (model == null)
                return View("Hata", "Kayıt bulunamadı!");
            return View(model);
        }

        #region IActionResult'ı implemente eden class'lar
        /*
        IActionResult
        ActionResult
        ViewResult (View())  ContentResult (Content()) EmptyResult   FileContentResult (File()) HttpResults JavaScriptResult (JavaScript())  JsonResult (Json())   RedirectResults
        */
        public ContentResult GetHtmlContent()
        {
            //return new ContentResult();
            return Content("<b><i>Content result.</i></b>", "text/html");
        }
        public ActionResult GetKategorilerXmlContent() // XML döndürme işlemleri genelde bu şekilde yapılmaz, web servisler üzerinden döndürülür!
        {
            List<KategoriModel> kategoriler = _kategoriService.Query().ToList();
            string xml = "<?xml version=\"1.0\" encoding=\"utf-8\" ?>";
            xml += "<KategoriModels>";
            foreach (KategoriModel kategori in kategoriler)
            {
                xml += "<KategoriModel>";
                xml += "<Id>" + kategori.Id + "</Id>";
                xml += "<Adi>" + kategori.Adi + "</Adi>";
                xml += "<Aciklamasi>" + kategori.Aciklamasi + "</Aciklamasi>";
                xml += "</KategoriModel>";
            }
            xml += "</KategoriModels>";
            return Content(xml, "application/xml");
        }
        public string GetString()
        {
            return "String.";
        }
        public EmptyResult GetEmpty()
        {
            return new EmptyResult();
        }
        #endregion
    }
}

MvcWebUI/Views/Kategoriler/Details.cshtml
@*@model DataAccess.Entities.Kategori*@
@model KategoriModel

@{
    //ViewData["Title"] = "Details";
    ViewData["Title"] = "Kategori Detayı";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Kategori</h4>
    <hr />
    <dl class="row">
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Adi) @* Özelliğin varsa display name'i yoksa adı: Adı *@
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Adi) @* Özelliğin verisi *@
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Aciklamasi)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Aciklamasi)
        </dd>

        @*<dt class="col-2">
            @Html.DisplayNameFor(model => model.Guid)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Guid)
        </dd>*@

        <dt class="col-2">
            @Html.DisplayNameFor(model => model.UrunSayisiDisplay)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.UrunSayisiDisplay)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Düzenle</a>&nbsp;|&nbsp;
    <a asp-action="Index">Kategori Listesi</a>
</div>

MvcWebUI/Views/Kategoriler/Edit.cshtml
@*
    ~/Views/_ViewStart.cshtml'de Layout değişkeni projenin _Layout.cshtml'ine set edildiği için view'lar
    scaffold edilirken her seferinde layout seçilmesine gerek yoktur.
*@

@*@model DataAccess.Entities.Kategori*@
@model KategoriModel

@{
    //ViewData["Title"] = "Edit";
    ViewData["Title"] = "Kategori Düzenle";
}

<h1>@ViewData["Title"]</h1>

@* Kategoriler controller'ının Edit post action'ında ViewBag.Error set ediliyor ve burada kullanılıyor. *@
@*@if (ViewData["Error"] != null)*@
@if (ViewBag.Error != null)
{
    <p class="text-danger">
        @ViewBag.Error
    </p>
}

<h4>Kategori</h4>
<hr />
<div class="row">
    <div class="col-12">

        @* Tag Helper *@
        @*<form asp-action="Edit">*@
        @* form tag helper'ında method yazılmazsa default post'tur. *@

        @* HTML Helper *@
        @*@using (Html.BeginForm("Edit", "Kategoriler", FormMethod.Post)) *@

        @*@using (Html.BeginForm("Edit", "Kategoriler")) *@
        @* form HTML helper'ında method yazılmazsa default post'tur. *@

        @using (Html.BeginForm()) 
        @*
            Kategoriler controller'ı Edit action'ından geldiğini bildiği için 
            form verilerini Kategoriler controller'ının Edit action'ına post olarak gönderir. 
        *@
        { @* <form> *@

            @* HTML Helper *@
            @Html.AntiForgeryToken()

            @* Tag Helper *@
            @*<div asp-validation-summary="All" class="text-danger"></div>*@

            @* HTML Helper *@
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })

            <div class="row mb-3">

                @* Tag Helper *@
                @*<label asp-for="Adi" class="col-2 col-form-label"></label>*@

                @* HTML Helper *@
                @*@Html.Label("Adi", "Adı", new { @class="col-2 col-form-label" })*@
                @Html.LabelFor(model => model.Adi, new { @class="col-2 col-form-label" })
                
                <div class="col-5">

                    @* Tag Helper *@
                    @*<input asp-for="Adi" class="form-control" placeholder="Kategori adı giriniz..." />*@ @* model'deki özelliğin veri tipine göre otomatik input oluşturur. *@
                    @*<input asp-for="Adi" class="form-control" type="text" placeholder="Kategori adı giriniz..." />*@ @* textbox oluşturur. *@

                    @* HTML Helper *@
                    @*@Html.EditorFor(model => model.Adi)*@ @* model'deki özelliğin veri tipine göre otomatik input oluşturur. *@
                    @Html.TextBoxFor(model => model.Adi, new { @class = "form-control", placeholder = "Kategori adı giriniz..." }) @* textbox oluşturur. *@

                    @* Tag Helper *@
                    @*<span asp-validation-for="Adi" class="text-danger"></span>*@
                    @* HTML Helper *@
                    @Html.ValidationMessageFor(model => model.Adi, null, new { @class = "text-danger" })

                </div>
            </div>
            <div class="row mb-3">

                @* Tag Helper *@
                @*<label asp-for="Aciklamasi" class="col-2 col-form-label"></label>*@

                @* HTML Helper *@
                @Html.LabelFor(model => model.Aciklamasi, new { @class="col-2 col-form-label" })

                <div class="col-5">

                    @* Tag Helper *@
                    @*<input asp-for="Aciklamasi" class="form-control" />*@
                    @*<textarea asp-for="Aciklamasi" class="form-control" rows="3" placeholder="Kategori açıklaması giriniz..."></textarea>*@

                    @* HTML Helper *@
                    @Html.TextAreaFor(model => model.Aciklamasi, new { @class = "form-control", rows = "3", placeholder = "Kategori açıklaması giriniz..." })

                    @* Tag Helper *@
                    @*<span asp-validation-for="Aciklamasi" class="text-danger"></span>*@

                    @* HTML Helper *@
                    @Html.ValidationMessageFor(model => model.Aciklamasi, null, new { @class = "text-danger" })

                </div>
            </div>

            @* Tag Helper *@
            @*<input type="hidden" asp-for="Id" />*@

            @* HTML Helper *@
            @Html.HiddenFor(model => model.Id)

            @* <div class="row mb-3">
                <label asp-for="Guid" class="col-2 col-form-label"></label>
                <div class="col-5">
                <input asp-for="Guid" class="form-control" />
                <span asp-validation-for="Guid" class="text-danger"></span>
                </div>
                </div>*@

            <div class="row mb-3">
                <div class="offset-2 col-5">
                    <input type="submit" value="Kaydet" class="btn btn-primary" />
                    &nbsp;&nbsp;
                    <button type="reset" class="btn btn-outline-primary">Temizle</button>
                    &nbsp;&nbsp;

                    @* Tag Helper *@
                    @*<a asp-action="Index" asp-controller="Kategoriler">Kategori Listesi</a>*@
                    @*<a asp-action="Index">Kategori Listesi</a>*@

                    @* HTML Helper *@
                    @*@Html.ActionLink("Kategori Listesi", "Index", "Kategoriler")*@
                    @Html.ActionLink("Kategori Listesi", "Index")

                </div>
            </div>

            @*</form>*@

        } @* </form> *@

    </div>
</div>

@*
    ASP.NET Core MVC'deki Genel Kullanılan HTML Helper'lar:
    Html.TextBox
    Html.TextBoxFor
    Html.Password
    Html.PasswordFor
    Html.TextArea
    Html.TextAreaFor
    Html.CheckBox
    Html.CheckBoxFor
    Html.RadioButton
    Html.RadioButtonFor
    Html.DropDownList
    Html.DropDownListFor
    Html.ListBox
    Html.ListBoxFor
    Html.Hidden
    Html.HiddenFor
    Html.Editor
    Html.EditorFor
    Html.Display
    Html.DisplayFor
    Html.Label
    Html.LabelFor
    Html.ActionLink
    Html.BeginForm
*@

MvcWebUI/Views/Kategoriler/KategoriListesi.cshtml
@* List<KategoriModel> Model; *@
@*@model List<Business.Models.KategoriModel>*@ @* View'da Model objesi olarak kullanılır. *@
@* 
    Her seferinde class'ın namespace'i üzerinden kullanılması yerine 
    ~/Views/_ViewImports.cshtml dosyasına namespace için using eklenerek direkt 
    tip adı kullanılabilir.
*@
@model List<KategoriModel>

<h2>Kategoriler</h2>
<br />

<p>
    <a href="/Kategoriler/OlusturGetir">Yeni Kategori</a>
</p>

@if (Model != null && Model.Count > 0)
{
    <p class="bg-info text-black">
        @Model.Count kayıt bulundu
    </p>
}
else
{
    <p class="bg-warning text-black">
        Kayıt bulunamadı
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                Adı
            </th>
            <th>
                Açıklaması
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
    @if (Model != null && Model.Count > 0)
    {
        foreach (KategoriModel kategori in Model)
        {
            <tr>
                <td>
                    @kategori.Adi
                </td>
                <td>
                    @kategori.Aciklamasi
                </td>
                <td style="text-align: right;">
                    <a href="/Kategoriler/Edit/@kategori.Id">Düzenle</a>&nbsp;|&nbsp;
                    <a href="/Kategoriler/Delete/@kategori.Id">Sil</a>&nbsp;|&nbsp;
                    <a href="/Kategoriler/Details/@kategori.Id">Detay</a>
                </td>
            </tr>
        }
    }
    </tbody>
</table>

@* Kategoriler controller'ının Edit post ve Delete get action'larında TempData["Success"] set ediliyor ve burada kullanılıyor. *@
@if (TempData["Success"] != null)
{
    <p class="bg-success text-white">
        @TempData["Success"]
    </p>
}

@* Kategoriler controller'ının Delete get action'ında TempData["Error"] set ediliyor ve burada kullanılıyor. *@
@if (TempData["Error"] != null)
{
    <p class="bg-danger text-white">
        @TempData["Error"]
    </p>
}

MvcWebUI/Views/Kategoriler/OlusturHtml.cshtml
<h2>Yeni Kategori</h2>

<!-- 
HTML formlarında eğer method yazılmazsa default olarak get'tir. get methodu form verilerinin bir query string 
üzerinden action olarak belirtilen adrese gönderilmesini sağlar: 
~/Kategoriler/OlusturGonder?Adi=Araba&Aciklamasi=Binek
Eğer method post olarak kullanılırsa form verileri query string üzerinden değil direkt sunucuya gönderilir,
dolayısıyla tarayıcının adres çubuğunda veriler görünmez:
~/Kategoriler/OlusturGonder
-->
@*<form action="/Kategoriler/OlusturGonder" method="get">*@
<form action="/Kategoriler/OlusturGonder" method="post">

    <div class="mb-3 mt-3">
        <label for="adi" class="form-label">Adı:</label>
        <input type="text" class="form-control" id="adi" placeholder="Kategori adı giriniz..." name="Adi">
    </div>
     <div class="mb-3">
        <label for="aciklamasi" class="form-label">Açıklaması:</label>
        <textarea class="form-control" id="aciklamasi" placeholder="Kategori açıklaması giriniz..." name="Aciklamasi"></textarea>
    </div>

    @*<input type="submit" class="btn btn-primary" value="Kaydet" />*@
    <button type="submit" class="btn btn-primary">Kaydet</button>

    &nbsp;
    <button type="reset" class="btn btn-warning">Temizle</button>

</form>